
server:
    port: 8083

spring:
    # datasource:
    #     url: jdbc:mysql://${DB_HOST:}:3306/${DB_NAME:}
    #     username: ${DB_USERNAME:}
    #     password: ${DB_PASSWORD:}
      
    # jpa:
    #     show-sql: true
    #     hibernate:
    #         ddl-auto: update
  

payaza:
    url.createDynamicVirtual: https://router-live.78financials.com/api/request/secure/payloadhandler
    secret.key: PZ78-PKLIVE-0E3EEBF6-B58B-4DD2-9C78-99D1E61945F8
  
